version: 2
jobs:
  build:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build application Docker image
          command: |
            docker build -t node-hcrypt .